baseURL = "https://wmc1999.top/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "OneStep"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

[params]
# LoveIt 主题版本
version = "0.2.X"

description = "用尽全力，活成一个普通人"

keywords = ["技术", "笔记"]

defaultTheme = "auto"

fingerprint = ""

dateFormat = "2006-01-02"

# LoveIt 新增 | 0.2.0 应用图标配置
[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "OneStep"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10磁贴颜色
tileColor = "#da532c"

[params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# LoveIt 新增 | 0.2.1 最大结果数目
maxResultLength = 10
# LoveIt 新增 | 0.2.3 结果内容片段长度
snippetLength = 50
# LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false

[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = "/images/logo.jpeg"
# 标题名称
name = "OneStep"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
typeit = false

[params.footer]
enable = true
# LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
custom = ''
# LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
hugo = true
# LoveIt 新增 | 0.2.0 是否显示版权信息
copyright = true
# LoveIt 新增 | 0.2.0 是否显示作者
author = true
# 网站创立年份
since = 2019
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.section]
# section 页面每页显示文章数量
paginate = 15
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10


[params.home]
# LoveIt 新增 | 0.2.0 RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = "images/avatar.jpeg"
# LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
title = ""
# 主页显示的网站副标题
subtitle = "欢迎来到我的Blog"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 5

[params.social]
GitHub = "waruto210"
Linkedin = ""
Twitter = "Jason210314"
Instagram = ""
Facebook = ""
Telegram = ""
Medium = ""
Gitlab = ""
Youtubelegacy = ""
Youtubecustom = ""
Youtubechannel = ""
Tumblr = ""
Quora = ""
Keybase = ""
Pinterest = ""
Reddit = ""
Codepen = ""
FreeCodeCamp = ""
Bitbucket = ""
Stackoverflow = ""
Weibo = ""
Odnoklassniki = ""
VK = ""
Flickr = ""
Xing = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Bandcamp = ""
Paypal = ""
Fivehundredpx = ""
Mix = ""
Goodreads = ""
Lastfm = ""
Foursquare = ""
Hackernews = ""
Kickstarter = ""
Patreon = ""
Steam = ""
Twitch = ""
Strava = ""
Skype = ""
Whatsapp = ""
Zhihu = ""
Douban = ""
Angellist = ""
Slidershare = ""
Jsfiddle = ""
Deviantart = ""
Behance = ""
Dribbble = ""
Wordpress = ""
Vine = ""
Googlescholar = ""
Researchgate = ""
Mastodon = ""
Thingiverse = ""
Devto = ""
Gitea = ""
XMPP = ""
Matrix = ""
Bilibili = ""
Email = "wmc314@outlook.com"
RSS = true

[params.page]
# LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
hiddenFromHomePage = false
# LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
# LoveIt 新增 | 0.2.0 是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = false
# LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
ruby = true
# LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
fraction = true
# LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
fontawesome = true
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
# LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
rssFullText = false

[params.page.toc]
# 是否使用目录
enable = true
# LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
keepStatic = true
# 是否使侧边目录自动折叠展开
auto = true

[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 10

[params.page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true

[params.page.share]
enable = true
Twitter = true
Facebook = false
Linkedin = false
Whatsapp = false
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = false
VK = false
Buffer = false
Xing = false
Line = false
Instapaper = false
Pocket = false
Digg = false
Stumbleupon = false
Flipboard = false
Weibo = false
Renren = false
Myspace = false
Blogger = false
Baidu = false
Odnoklassniki = false
Evernote = false
Skype = false
Trello = false
Mix = false

[params.page.comment]
enable = true

[params.page.comment.disqus]
# LoveIt 新增 | 0.1.1
enable = true
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = "wmc1999"

# LoveIt 新增 | 0.2.5 TypeIt 配置
[params.typeit]
# 每一步的打字速度 (单位是毫秒)
speed = 100
# 光标的闪烁速度 (单位是毫秒)
cursorSpeed = 1000
# 光标的字符 (支持 HTML 格式)
cursorChar = "|"
# 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
duration = -1

[params.seo]
# 图片 URL
image = ""
# 缩略图 URL
thumbnailUrl = ""

[params.analytics]
enable = false
# Google Analytics
[params.analytics.google]
id = "UA-164518488-1"
# 是否匿名化用户 IP
anonymizeIP = true

[params.cookieconsent]
enable = false
# 用于 Cookie 许可横幅的文本字符串
[params.cookieconsent.content]
message = ""
dismiss = ""
link = ""

[menu]
[[menu.main]]
identifier = "home"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "首页"
url = "/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 2
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 3
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 4

[[menu.main]]
identifier = "friendlinks"
pre = ""
post = ""
name = "友链"
url = "/friendlinks"
title = ""
weight = 5

[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "关于"
url = "/about"
title = ""
weight = 6

# Hugo 解析文档的配置
[markup]
# 语法高亮设置
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false 是必要的设置
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# 是否在文档中直接使用 HTML 标签
unsafe = true
# 目录设置
[markup.tableOfContents]
startLevel = 2
endLevel = 6

# 作者配置
[author]
name = "waruto210"
email = "wmc314@outlook.com"
link = "https://github.com/waruto210"

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
